name: Build & Deploy Docker image

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: caloverflow
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Set Versions
        uses: actions/github-script@v4
        id: get_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            core.setOutput('no-v', no_v)

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "caloverflow/python3.8-opencv-aws-lambda-layer:latest,cal-overflow/python3.8-opencv-aws-lambda-layer:${{ steps.get_version.outputs.no-v }}"

